// Common status constants
export enum UserRole {
  STUDENT = 'STUDENT',
  INSTRUCTOR = 'INSTRUCTOR',
  DEPARTMENT = 'DEPARTMENT',
  ADMIN = 'ADMIN',
}

export enum TopicType {
  DCLV = 'DCLV',
  DACN = 'DACN',
  DAMHKTMT = 'DAMHKTMT',
  LVTN = 'LVTN',
  DATN = 'DATN',
}

export enum TopicStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  FULL = 'FULL',
}

export enum RegistrationStatus {
  PENDING_INSTRUCTOR_REVIEW = 'PENDING_INSTRUCTOR_REVIEW',
  INSTRUCTOR_ACCEPTED = 'INSTRUCTOR_ACCEPTED',
  INSTRUCTOR_DENIED = 'INSTRUCTOR_DENIED',
  VERIFIED = 'VERIFIED',
  INVALID_CREDITS = 'INVALID_CREDITS',
  NOT_ENROLLED_EDUSOFT = 'NOT_ENROLLED_EDUSOFT',
  DEPARTMENT_REVOKED = 'DEPARTMENT_REVOKED',
}
