import {
  ThesisTopic,
  ThesisApplication,
  Student,
  Instructor,
  Admin,
  EDUSoftStudent,
  Notification,
} from '../types';

// Mock Users
export const mockStudents: Student[] = [
  {
    id: 'student-1',
    name: 'Alice Johnson',
    email: 'alice.johnson@university.edu',
    role: 'student',
    studentId: 'STU001',
    major: 'Computer Science',
    creditsCompleted: 120,
    englishProficiency: true,
  },
  {
    id: 'student-2',
    name: 'Bob Smith',
    email: 'bob.smith@university.edu',
    role: 'student',
    studentId: 'STU002',
    major: 'Software Engineering',
    creditsCompleted: 115,
    englishProficiency: true,
  },
  {
    id: 'student-3',
    name: 'Carol Williams',
    email: 'carol.williams@university.edu',
    role: 'student',
    studentId: 'STU003',
    major: 'Data Science',
    creditsCompleted: 95,
    englishProficiency: false,
  },
];

export const mockInstructors: Instructor[] = [
  {
    id: 'instructor-1',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@university.edu',
    role: 'instructor',
    department: 'Computer Science',
    researchAreas: ['Machine Learning', 'Computer Vision'],
  },
  {
    id: 'instructor-2',
    name: 'Dr. Sarah Brown',
    email: 'sarah.brown@university.edu',
    role: 'instructor',
    department: 'Software Engineering',
    researchAreas: ['Software Architecture', 'DevOps'],
  },
  {
    id: 'instructor-3',
    name: 'Dr. James Wilson',
    email: 'james.wilson@university.edu',
    role: 'instructor',
    department: 'Data Science',
    researchAreas: ['Big Data', 'Data Mining'],
  },
];

export const mockAdmins: Admin[] = [
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@university.edu',
    role: 'admin',
    department: 'Academic Affairs',
  },
];

// Mock Topics
export const mockTopics: ThesisTopic[] = [
  {
    id: 'topic-1',
    topicCode: 'HK251-LVTN-001',
    topicType: 'LVTN',
    title: 'Ứng dụng Deep Learning trong phân tích hình ảnh y khoa',
    titleEn: 'Deep Learning for Medical Image Analysis',
    description:
      'Nghiên cứu ứng dụng các kỹ thuật deep learning để phát hiện bệnh trong hình ảnh y khoa như X-quang và MRI. Đề tài tập trung vào việc xây dựng và đánh giá các mô hình CNN cho việc phân loại và phát hiện bất thường trong hình ảnh y tế.',
    instructorId: 'instructor-1',
    instructorName: 'Michael Chen',
    instructorTitle: 'TS.',
    instructorEmployeeId: '003282',
    instructorEmail: 'michael.chen@university.edu',
    instructorDepartment: 'Khoa Khoa học Máy tính',
    requiredSkills: ['Python', 'TensorFlow/PyTorch', 'Computer Vision', 'Linear Algebra'],
    researchArea: 'Machine Learning',
    totalSlots: 3,
    availableSlots: 2,
    pendingApplications: 1,
    status: 'Active',
    programTypes: ['CQ', 'CN'],
    department: 'Computer Science',
    phase1Requirements:
      'Tìm hiểu các kiến trúc CNN phổ biến (ResNet, VGG, U-Net). Nghiên cứu các bộ dataset y khoa công khai. Xây dựng baseline model và đánh giá hiệu suất ban đầu.',
    phase2Requirements:
      'Cải tiến mô hình với các kỹ thuật augmentation và transfer learning. Triển khai hệ thống phát hiện bệnh với giao diện web. Đánh giá toàn diện với các metrics y khoa (Sensitivity, Specificity, AUC-ROC).',
    references: [
      'LeCun, Y., Bengio, Y., & Hinton, G. (2015). Deep learning. Nature, 521(7553), 436-444.',
      'Ronneberger, O., Fischer, P., & Brox, T. (2015). U-Net: Convolutional Networks for Biomedical Image Segmentation.',
      'Rajpurkar, P., et al. (2017). CheXNet: Radiologist-Level Pneumonia Detection on Chest X-Rays with Deep Learning.',
    ],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'topic-2',
    topicCode: 'HK251-LVTN-002',
    topicType: 'LVTN',
    title: 'Nghiên cứu và triển khai các mẫu kiến trúc Microservices',
    titleEn: 'Microservices Architecture Patterns',
    description:
      'Nghiên cứu và triển khai các mẫu thiết kế microservices cho ứng dụng doanh nghiệp có khả năng mở rộng. Đề tài bao gồm việc thiết kế, triển khai và đánh giá hiệu suất của các hệ thống phân tán.',
    instructorId: 'instructor-2',
    instructorName: 'Sarah Brown',
    instructorTitle: 'PGS. TS.',
    instructorEmployeeId: '003145',
    instructorEmail: 'sarah.brown@university.edu',
    instructorDepartment: 'Khoa Công nghệ Phần mềm',
    requiredSkills: ['Docker', 'Kubernetes', 'REST APIs', 'Spring Boot/Node.js', 'SQL/NoSQL'],
    researchArea: 'Software Architecture',
    totalSlots: 2,
    availableSlots: 1,
    pendingApplications: 2,
    status: 'Active',
    programTypes: ['CQ', 'CN', 'B2'],
    department: 'Software Engineering',
    phase1Requirements:
      'Tìm hiểu các mẫu thiết kế microservices (Saga, CQRS, Event Sourcing). Phân tích các case study từ các công ty lớn (Netflix, Uber). Thiết kế kiến trúc hệ thống demo.',
    phase2Requirements:
      'Triển khai hệ thống microservices hoàn chỉnh với ít nhất 5 services. Implement CI/CD pipeline. Thực hiện load testing và performance optimization. Viết tài liệu kiến trúc chi tiết.',
    references: [
      'Newman, S. (2021). Building Microservices: Designing Fine-Grained Systems. O\'Reilly Media.',
      'Richardson, C. (2018). Microservices Patterns: With Examples in Java. Manning Publications.',
      'Fowler, M. (2014). Microservices - a definition of this new architectural term.',
    ],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: 'topic-3',
    topicCode: 'HK251-ĐATN-003',
    topicType: 'ĐATN',
    title: 'Xử lý dữ liệu thời gian thực với Apache Kafka',
    titleEn: 'Real-time Data Processing with Apache Kafka',
    description:
      'Xây dựng pipeline xử lý dữ liệu thời gian thực sử dụng Apache Kafka cho việc xử lý streaming data. Đề tài hướng đến việc thiết kế và triển khai hệ thống có khả năng xử lý hàng triệu events mỗi giây.',
    instructorId: 'instructor-3',
    instructorName: 'James Wilson',
    instructorTitle: 'ThS.',
    instructorEmployeeId: '003567',
    instructorEmail: 'james.wilson@university.edu',
    instructorDepartment: 'Khoa Khoa học Dữ liệu',
    requiredSkills: ['Java', 'Apache Kafka', 'Distributed Systems', 'Stream Processing', 'Docker'],
    researchArea: 'Big Data',
    totalSlots: 4,
    availableSlots: 4,
    pendingApplications: 0,
    status: 'Active',
    programTypes: ['CQ', 'CN', 'SN'],
    department: 'Data Science',
    phase1Requirements:
      'Nghiên cứu kiến trúc Apache Kafka và các concepts cơ bản. Tìm hiểu Kafka Streams và KSQL. Thiết kế use case cụ thể (real-time analytics, event-driven architecture).',
    phase2Requirements:
      'Triển khai Kafka cluster với monitoring (Prometheus, Grafana). Xây dựng producer và consumer applications. Implement exactly-once semantics. Benchmark và optimize performance.',
    references: [
      'Narkhede, N., Shapira, G., & Palino, T. (2017). Kafka: The Definitive Guide. O\'Reilly Media.',
      'Kleppmann, M. (2017). Designing Data-Intensive Applications. O\'Reilly Media.',
      'Stopford, B. (2018). Designing Event-Driven Systems. O\'Reilly Media.',
    ],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'topic-4',
    topicCode: 'HK251-LVTN-004',
    topicType: 'LVTN',
    title: 'Xử lý ngôn ngữ tự nhiên cho phân tích cảm xúc',
    titleEn: 'Natural Language Processing for Sentiment Analysis',
    description:
      'Phát triển các mô hình NLP để phân tích cảm xúc trong bài đăng mạng xã hội và đánh giá sản phẩm. Đề tài tập trung vào việc xây dựng mô hình có thể xử lý tiếng Việt và đánh giá đa chiều.',
    instructorId: 'instructor-1',
    instructorName: 'Michael Chen',
    instructorTitle: 'TS.',
    instructorEmployeeId: '003282',
    instructorEmail: 'michael.chen@university.edu',
    instructorDepartment: 'Khoa Khoa học Máy tính',
    requiredSkills: ['Python', 'NLP', 'Deep Learning', 'BERT/Transformers', 'PyTorch'],
    researchArea: 'Machine Learning',
    totalSlots: 2,
    availableSlots: 0,
    pendingApplications: 0,
    status: 'Full',
    programTypes: ['CQ', 'CN'],
    department: 'Computer Science',
    phase1Requirements:
      'Tìm hiểu các phương pháp NLP truyền thống và hiện đại. Thu thập và tiền xử lý dataset tiếng Việt. Xây dựng baseline với các mô hình cơ bản (LSTM, GRU).',
    phase2Requirements:
      'Fine-tune các pre-trained models (PhoBERT, mBERT). Xây dựng aspect-based sentiment analysis. Triển khai API và demo application. So sánh hiệu suất với các phương pháp khác.',
    references: [
      'Devlin, J., et al. (2019). BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding.',
      'Nguyen, D. Q., & Nguyen, A. T. (2020). PhoBERT: Pre-trained language models for Vietnamese.',
      'Zhang, L., Wang, S., & Liu, B. (2018). Deep learning for sentiment analysis: A survey.',
    ],
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-13'),
  },
];

// Mock Applications
export const mockApplications: ThesisApplication[] = [
  {
    id: 'app-1',
    studentId: 'STU001',
    studentName: 'Alice Johnson',
    studentEmail: 'alice.johnson@university.edu',
    topicId: 'topic-1',
    topicTitle: 'Deep Learning for Medical Image Analysis',
    instructorId: 'instructor-1',
    instructorName: 'Dr. Michael Chen',
    status: 'PENDING_INSTRUCTOR_REVIEW',
    selfReportedCredits: 120,
    motivationLetter:
      'I am passionate about applying AI to healthcare and have completed relevant coursework in machine learning.',
    documents: [
      {
        id: 'doc-1',
        name: 'transcript.pdf',
        type: 'application/pdf',
        url: '/uploads/transcript.pdf',
        uploadedAt: new Date('2024-01-15'),
      },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'app-2',
    studentId: 'STU002',
    studentName: 'Bob Smith',
    studentEmail: 'bob.smith@university.edu',
    topicId: 'topic-2',
    topicTitle: 'Microservices Architecture Patterns',
    instructorId: 'instructor-2',
    instructorName: 'Dr. Sarah Brown',
    status: 'INSTRUCTOR_ACCEPTED',
    selfReportedCredits: 115,
    actualCredits: 115,
    motivationLetter:
      'I have extensive experience with Docker and Kubernetes from my internship.',
    documents: [
      {
        id: 'doc-2',
        name: 'transcript.pdf',
        type: 'application/pdf',
        url: '/uploads/transcript2.pdf',
        uploadedAt: new Date('2024-01-16'),
      },
    ],
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-17'),
    instructorNotes: 'Strong candidate with relevant experience.',
  },
  {
    id: 'app-3',
    studentId: 'STU003',
    studentName: 'Carol Williams',
    studentEmail: 'carol.williams@university.edu',
    topicId: 'topic-2',
    topicTitle: 'Microservices Architecture Patterns',
    instructorId: 'instructor-2',
    instructorName: 'Dr. Sarah Brown',
    status: 'INSTRUCTOR_DENIED',
    selfReportedCredits: 95,
    motivationLetter: 'I want to learn about microservices.',
    documents: [
      {
        id: 'doc-3',
        name: 'transcript.pdf',
        type: 'application/pdf',
        url: '/uploads/transcript3.pdf',
        uploadedAt: new Date('2024-01-17'),
      },
    ],
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-18'),
    instructorNotes: 'Insufficient credits and missing prerequisite skills.',
  },
  {
    id: 'app-4',
    studentId: 'STU001',
    studentName: 'Alice Johnson',
    studentEmail: 'alice.johnson@university.edu',
    topicId: 'topic-4',
    topicTitle: 'Natural Language Processing for Sentiment Analysis',
    instructorId: 'instructor-1',
    instructorName: 'Dr. Michael Chen',
    status: 'VERIFIED',
    selfReportedCredits: 120,
    actualCredits: 120,
    motivationLetter: 'I have strong interest in NLP and have completed related projects.',
    documents: [
      {
        id: 'doc-4',
        name: 'transcript.pdf',
        type: 'application/pdf',
        url: '/uploads/transcript4.pdf',
        uploadedAt: new Date('2024-01-10'),
      },
    ],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-20'),
    instructorNotes: 'Excellent candidate.',
    departmentNotes: 'Verified against EDUSoft records.',
  },
];

// Mock EDUSoft Data
export const mockEDUSoftData: EDUSoftStudent[] = [
  {
    studentId: 'STU001',
    name: 'Alice Johnson',
    major: 'Computer Science',
    enrolledInThesis: true,
    actualCredits: 120,
    englishProficiency: true,
    semester: 'Fall 2024',
  },
  {
    studentId: 'STU002',
    name: 'Bob Smith',
    major: 'Software Engineering',
    enrolledInThesis: true,
    actualCredits: 115,
    englishProficiency: true,
    semester: 'Fall 2024',
  },
  {
    studentId: 'STU003',
    name: 'Carol Williams',
    major: 'Data Science',
    enrolledInThesis: false,
    actualCredits: 95,
    englishProficiency: false,
    semester: 'Fall 2024',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'student-1',
    title: 'Application Submitted',
    message: 'Your application for "Deep Learning for Medical Image Analysis" has been submitted.',
    type: 'success',
    read: false,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'notif-2',
    userId: 'instructor-1',
    title: 'New Application',
    message: 'Alice Johnson has applied for your topic "Deep Learning for Medical Image Analysis".',
    type: 'info',
    read: false,
    createdAt: new Date('2024-01-15'),
  },
];
